name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.friendlyName }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        arch:
          - x64
        include:
          - os: ubuntu-latest
            friendlyName: Linux
          - os: windows-latest
            friendlyName: Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        if: matrix.os != 'ubuntu-latest'
        run: npm test

      - name: Run tests under xvfb
        if: matrix.os == 'ubuntu-latest'
        run: xvfb-run npm test


