name: release
on:
  push:
    tags:
      - v*.*

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
